apiVersion: v1
kind: Secret
metadata:
  name: db-credentials

type: Opaque
stringData:
  DB_HOST: "db.local.example.com"
  DB_NAME: "task_manager"
  DB_USER: "taskuser"
  DB_PASSWORD: "StrongPassword123!"