## @param overrideConfiguration Kafka common configuration override. Values defined here takes precedence over the ones defined at `config`
##
overrideConfiguration:
  ## @param logflushintervalmessages the number of messages to accept before forcing a flush of data to disk
  ##
  log.flush.interval.messages: 10000
  ## @param logflushintervalms the maximum amount of time a message can sit in a log before we force a flush
  ##
  log.flush.interval.ms: 1000
  ## @param logretentionbytes a size-based retention policy for logs
  ##
  log.retention.bytes: 1073741824
  ## @param logretentionhours the minimum age of a log file to be eligible for deletion due to age
  ##
  log.retention.hours: 2
  ## @param offsetstopicreplicationfactor the replication factor for the offsets topic
  ##
  offsets.topic.replication.factor: 1
  ## @param transactionstatelogreplicationfactor the replication factor for the transaction topic
  ##
  transaction.state.log.replication.factor: 1
  ## @param transactionstatelogminisr overridden min.insync.replicas config for the transaction topic
  ##
  transaction.state.log.min.isr: 1
  ## @param numpartitions the default number of log partitions per topic
  ##
  num.partitions: 2
  ## @param numrecoverythreadsperdatadir the number of threads per data directory to be used for log recovery at startup and flushing at shutdown
  ##
  num.recovery.threads.per.data.dir: 1
  ## @param alloweveryoneifnoaclfound by default, if a resource has no associated acls, then no one is allowed to access that resource except super users
  ##
  allow.everyone.if.no.acl.found: true

listeners:
  ## @param listeners.client.name Name for the Kafka client listener
  ## @param listeners.client.containerPort Port for the Kafka client listener
  ## @param listeners.client.protocol Security protocol for the Kafka client listener. Allowed values are 'PLAINTEXT', 'SASL_PLAINTEXT', 'SASL_SSL' and 'SSL'
  ## @param listeners.client.sslClientAuth Optional. If SASL_SSL is enabled, configure mTLS TLS authentication type. If SSL protocol is enabled, overrides tls.authType for this listener. Allowed values are 'none', 'requested' and 'required'
  client:
    protocol: PLAINTEXT
  ## @param listeners.controller.name Name for the Kafka controller listener
  ## @param listeners.controller.containerPort Port for the Kafka controller listener
  ## @param listeners.controller.protocol Security protocol for the Kafka controller listener. Allowed values are 'PLAINTEXT', 'SASL_PLAINTEXT', 'SASL_SSL' and 'SSL'
  ## @param listeners.controller.sslClientAuth Optional. If SASL_SSL is enabled, configure mTLS TLS authentication type. If SSL protocol is enabled, overrides tls.authType for this listener. Allowed values are 'none', 'requested' and 'required'
  ## Ref: https://cwiki.apache.org/confluence/display/KAFKA/KIP-684+-+Support+mutual+TLS+authentication+on+SASL_SSL+listeners
  controller:
    protocol: PLAINTEXT
  ## @param listeners.interbroker.name Name for the Kafka inter-broker listener
  ## @param listeners.interbroker.containerPort Port for the Kafka inter-broker listener
  ## @param listeners.interbroker.protocol Security protocol for the Kafka inter-broker listener. Allowed values are 'PLAINTEXT', 'SASL_PLAINTEXT', 'SASL_SSL' and 'SSL'
  ## @param listeners.interbroker.sslClientAuth Optional. If SASL_SSL is enabled, configure mTLS TLS authentication type. If SSL protocol is enabled, overrides tls.authType for this listener. Allowed values are 'none', 'requested' and 'required'
  interbroker:
    protocol: PLAINTEXT
  ## @param listeners.external.containerPort Port for the Kafka external listener
  ## @param listeners.external.protocol Security protocol for the Kafka external listener. . Allowed values are 'PLAINTEXT', 'SASL_PLAINTEXT', 'SASL_SSL' and 'SSL'
  ## @param listeners.external.name Name for the Kafka external listener
  ## @param listeners.external.sslClientAuth Optional. If SASL_SSL is enabled, configure mTLS TLS authentication type. If SSL protocol is enabled, overrides tls.sslClientAuth for this listener. Allowed values are 'none', 'requested' and 'required'
  external:
    protocol: PLAINTEXT


tls:
  ## @param tls.autoGenerated.enabled Enable automatic generation of TLS certificates (only supported if `tls.type` is `PEM`) # @param tls.autoGenerated.engine Mechanism to generate the certificates (allowed values: helm, cert-manager)
  ## @param tls.autoGenerated.customAltNames List of additional subject alternative names (SANs) for the automatically generated TLS certificates.
  ## @param tls.autoGenerated.certManager.existingIssuer The name of an existing Issuer to use for generating the certificates (only for `cert-manager` engine)
  ## @param tls.autoGenerated.certManager.existingIssuerKind Existing Issuer kind, defaults to Issuer (only for `cert-manager` engine)
  ## @param tls.autoGenerated.certManager.keyAlgorithm Key algorithm for the certificates (only for `cert-manager` engine)
  ## @param tls.autoGenerated.certManager.keySize Key size for the certificates (only for `cert-manager` engine)
  ## @param tls.autoGenerated.certManager.duration Duration for the certificates (only for `cert-manager` engine)
  ## @param tls.autoGenerated.certManager.renewBefore Renewal period for the certificates (only for `cert-manager` engine)
  ##
  autoGenerated:
    enabled: true
    engine: cert-manager
    certManager:
      existingIssuer: "my-ca-issuer"
      existingIssuerKind: "ClusterIssuer"

## @section Controller-eligible statefulset parameters
##
controller:
  ## @param controller.replicaCount Number of Kafka controller-eligible nodes
  ##
  replicaCount: 2

## Kafka Pod Disruption Budget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
## @param controller.pdb.create Deploy a pdb object for the Kafka pod
## @param controller.pdb.minAvailable Minimum number/percentage of available Kafka replicas
## @param controller.pdb.maxUnavailable Maximum number/percentage of unavailable Kafka replicas
##
pdb:
  create: false

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
##
persistence:
  ## @param controller.persistence.enabled Enable Kafka data persistence using PVC
  ##
  enabled: false

## Network policies
## Ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
##
networkPolicy:
  ## @param networkPolicy.enabled Specifies whether a NetworkPolicy should be created
  ##
  enabled: false
